### ISSUE TITLE
Error of build on Debian

### ISSUE THREAD

**Issue by Kcchouette** [airdcpp-web/airdcpp-webclient#166]
### Current UI and client versions:

Not yet installed, I'm trying to compile it.

### Steps to reproduce the issue:

1. debian 8 64bit
2. clone the depo
3. `cmake .`

You'll have an error: `Installing Web UI (~1.0.0)
CMake Error at CMakeLists.txt:243 (message):
  Failed to install Web UI`

Here CMakeError.log:

```
CMakeFiles/cmTryCompileExec628214981.dir/build.make:57: recipe for target 'CMakeFiles/cmTryCompileExec628214981.dir/src.cxx.o' failed
make[1]: *** [CMakeFiles/cmTryCompileExec628214981.dir/src.cxx.o] Error 1
make[1]: Leaving directory '/home/user/projects/airdcpp-webclient/CMakeFiles/CMakeTmp'
Makefile:118: recipe for target 'cmTryCompileExec628214981/fast' failed
make: *** [cmTryCompileExec628214981/fast] Error 2

Source file was:

  #include <iconv.h>
  int main(){
    iconv_t conv = 0;
    const char* in = 0;
    size_t ilen = 0;
    char* out = 0;
    size_t olen = 0;
    iconv(conv, &in, &ilen, &out, &olen);
    return 0;
  }
```
Thanks

**Comment by maksis** [comment]
Could you post the full cmake output from console?

**Comment by Kcchouette** [comment]
```
$ git clone https://github.com/airdcpp-web/airdcpp-webclient.git && cd airdcpp-webclient && cmake .

Cloning into 'airdcpp-webclient'...
remote: Counting objects: 18592, done.
remote: Compressing objects: 100% (38/38), done.
remote: Total 18592 (delta 14), reused 0 (delta 0), pack-reused 18553
Receiving objects: 100% (18592/18592), 6.39 MiB | 1.81 MiB/s, done.
Resolving deltas: 100% (15578/15578), done.
Checking connectivity... done.
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
-- Looking for mallinfo
-- Looking for mallinfo - found
-- Looking for malloc_stats
-- Looking for malloc_stats - found
-- Looking for malloc_trim
-- Looking for malloc_trim - found
-- Looking for include file mntent.h
-- Looking for include file mntent.h - found
-- Looking for 9 include files malloc.h, ..., unistd.h
-- Looking for 9 include files malloc.h, ..., unistd.h - found
-- Looking for 4 include files sys/socket.h, ..., sys/types.h
-- Looking for 4 include files sys/socket.h, ..., sys/types.h - found
-- Looking for 5 include files sys/types.h, ..., stdint.h
-- Looking for 5 include files sys/types.h, ..., stdint.h - found
-- Found LibGeoIP: /usr/lib/x86_64-linux-gnu/libGeoIP.so  
-- Performing Test HAVE_GEOIP_COUNTRY_EDITION_V6
-- Performing Test HAVE_GEOIP_COUNTRY_EDITION_V6 - Success
-- Performing Test HAVE_GEOIP_CITY_EDITION_REV0_V6
-- Performing Test HAVE_GEOIP_CITY_EDITION_REV0_V6 - Success
-- Found BZip2: /usr/lib/x86_64-linux-gnu/libbz2.so (found version "1.0.6") 
-- Looking for BZ2_bzCompressInit in /usr/lib/x86_64-linux-gnu/libbz2.so
-- Looking for BZ2_bzCompressInit in /usr/lib/x86_64-linux-gnu/libbz2.so - found
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.1t") 
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Iconv: /usr/lib/x86_64-linux-gnu/libc.so  
-- Performing Test ICONV_SECOND_ARGUMENT_IS_CONST
-- Performing Test ICONV_SECOND_ARGUMENT_IS_CONST - Failed
-- Found Miniupnpc: /usr/lib/x86_64-linux-gnu/libminiupnpc.so  
-- Found libnatpmp: /usr/lib/libnatpmp.so
-- Found Git: /usr/bin/git (found version "2.1.4") 
-- Found LevelDB: /usr/lib/x86_64-linux-gnu/libleveldb.so
-- Looking for backtrace
-- Looking for backtrace - found
-- backtrace facility detected in default set of libraries
-- Found Backtrace: /usr/include  
-- Found Intel TBB
-- Building with UPNP support (miniupnpc)
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   regex
--   system
--   thread
-- Library directory: /usr/local/lib
-- Resource directory: /usr/local/share/airdcpp/
-- Version file generated
-- StringDefs.cpp was generated
-- Stacktrace enabled
-- addr2line enabled
-- CMAKE_SYSTEM: Linux-3.16.0-4-amd64
-- CMAKE_SYSTEM_PROCESSOR: x86_64
-- CMAKE_CXX_COMPILER_ID: GNU
-- CMAKE_CXX_COMPILER_VERSION: 4.9.2
-- CMAKE_C_COMPILER_ID: GNU
-- CMAKE will use this libs (and headers) during build:
    miniupnpc (headers):/usr/lib/x86_64-linux-gnu/libminiupnpc.so (/usr/include)
    boost (headers): /usr/lib/x86_64-linux-gnu/libboost_regex.so;/usr/lib/x86_64-linux-gnu/libboost_system.so;/usr/lib/x86_64-linux-gnu/libboost_thread.so;/usr/lib/x86_64-linux-gnu/libpthread.so (/usr/include)
    bzip2 (headers): /usr/lib/x86_64-linux-gnu/libbz2.so (/usr/include)
    zlib (headers): /usr/lib/x86_64-linux-gnu/libz.so (/usr/include)
    openssl (headers): /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (/usr/include)
    iconv (headers): /usr/lib/x86_64-linux-gnu/libc.so (/usr/include)
    geoip (headers): /usr/lib/x86_64-linux-gnu/libGeoIP.so (/usr/include)
    leveldb (headers): /usr/lib/x86_64-linux-gnu/libleveldb.so (/usr/include)
    websocketpp (headers): (/usr/local/include)
    natpmp (headers): /usr/lib/libnatpmp.so (/usr/include)
    tbb (headers): /usr/lib/libtbb.so (/usr/include)
    
-- Installing Web UI
Installing Web UI (~1.0.0)
CMake Error at CMakeLists.txt:243 (message):
  Failed to install Web UI


-- Configuring incomplete, errors occurred!
See also "/home/user/projects/airdcpp-webclient/CMakeFiles/CMakeOutput.log".
See also "/home/user/projects/airdcpp-webclient/CMakeFiles/CMakeError.log".
```

Here my full console log :)

**Comment by maksis** [comment]
What's the output of the following command (run in the client directory):

`npm install airdcpp-webui@~1.0.0`

**Comment by Kcchouette** [comment]
```
$ npm install airdcpp-webui@~1.0.0
npm ERR! Error: Attempt to unlock airdcpp-webui@~1.0.0, which hasn't been locked
npm ERR!     at unlock (/usr/share/npm/lib/utils/locker.js:44:11)
npm ERR!     at cb (/usr/share/npm/lib/cache/add-named.js:32:5)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:41:20
npm ERR!     at /usr/share/npm/lib/utils/locker.js:22:20
npm ERR!     at /usr/share/npm/node_modules/inflight/inflight.js:22:7
npm ERR!     at Array.forEach (native)
npm ERR!     at res (/usr/share/npm/node_modules/inflight/inflight.js:21:9)
npm ERR!     at /usr/lib/nodejs/once.js:17:15
npm ERR!     at afterMkdir (/usr/share/npm/lib/cache/get-stat.js:53:14)
npm ERR!     at /usr/lib/nodejs/mkdirp/index.js:46:53
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "airdcpp-webui@~1.0.0"
npm ERR! cwd /home/user/projects/airdcpp-webclient
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/user/projects/airdcpp-webclient/npm-debug.log
npm ERR! not ok code 0
```

**Comment by maksis** [comment]
http://stackoverflow.com/questions/22152162/npm-cannot-install-dependencies-attempt-to-unlock-something-which-hasnt-been
https://github.com/npm/npm/issues/4815

Will those help to resolve that npm error?

**Comment by Kcchouette** [comment]
Here the solution: launch `cmake .` as root (and not as a normal user).

Thank you for your help!

**Comment by maksis** [comment]
The installation script should have been outputting errors during the UI installation... it has been fixed now
