### ISSUE TITLE
Server crash when "Loading form data"

### ISSUE THREAD

**Issue by NEMO1911** [airdcpp-web/airdcpp-webclient#175]
## Hardware:
- Raspberry PI 2 model B (2GB USB drive for SWAP)

## Software:
- AirDC++w 1.0.6 armv7l
- Web UI version 1.0.7
- Ubuntu 16.04 LTS (GNU/Linux 4.4.14-v7+ armv7l)
- Google Chrome Version 51.0.2704.106 m (64-bit)

## Notes:
- Fresh install of Ubuntu with everything updated 06/07/2016
- Fresh compile and install of AirDC++w from master 06/07/2016
- Installed all dependencies for "Ubuntu 15.10 or newer" https://airdcpp-web.github.io/docs/installation/dependencies-ubuntu.html

## Steps to reproduce crash:
- [x] successfully configured with airdcppd --configure
- [x] successfully started with airdcppd
- [x] successfully connected to http://192.168.X.X:5600
- [x] successfully connected to https://192.168.X.X:5601
- [x] successfully looged in with configured user and password
- [x] succesfully greated by settup message on home screen
- [ ] When clicking on the settings menu the browser shows "Loading form data" and the server crashes

![airdc w 06 07 2016-14 44 24](https://cloud.githubusercontent.com/assets/20353991/16684182/fbd412c4-4503-11e6-85de-1538714bed2a.png)

## Final notes
- terminal output [2016-07-06 14:42:56] - [2016-07-06 14:44:23] is occurring when connecting and while connected to server through the browser and moving around in the interface clicking menus.
- able to click on every other menu item without crashing the server except "Settings".
- able to check about tab by manualy typing in https://192.168.X.X:5601/settings/about.
- run "airdcppd" as root or normal user (No difference).
- trying http and https (No difference).
- this post AirDC++w 0.16.3 seam to have same problem: https://github.com/airdcpp-web/airdcpp-webclient/issues/83
- also worth mentoning this post https://github.com/airdcpp-web/airdcpp-webclient/issues/149
- crash information at the end of "Terminal output" is the same as stored in /home/xxxx/.airdc++/exceptioninfo.txt

## Terminal output (removed/changed personal stuff):
```
xxxx@xxxx:~$ airdcppd
Starting.
.Loading Hash database
Loading Download queue
Loading Shared files
Loading Country information
Starting web server.
AirDC++w 1.0.6 running, press ctrl-c to exit...
HTTP port: 0, HTTPS port: 5601
[2016-07-06 14:42:56] [error] handle_read_handshake error: websocketpp.transport:8 (TLS Short Read)
[2016-07-06 14:42:56] [fail] WebSocket Connection [::ffff:<client.adress>]:50690 - "" - 0 websocketpp.transport:8 TLS Short Read
[2016-07-06 14:43:04] [http] <server.adress>:5601 [::ffff:<client.adress>]:50691 "GET / HTTP/1.1" 200 994 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
[2016-07-06 14:43:04] [error] handle_read_handshake error: websocketpp.transport:8 (TLS Short Read)
[2016-07-06 14:43:04] [fail] WebSocket Connection [::ffff:<client.adress>]:50692 - "" - 0 websocketpp.transport:8 TLS Short Read
[2016-07-06 14:43:05] [http] <server.adress>:5601 [::ffff:<client.adress>]:50693 "GET /js/main.entry.js HTTP/1.1" 200 1833897 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
[2016-07-06 14:43:06] [error] handle_read_handshake error: websocketpp.transport:8 (TLS Short Read)
[2016-07-06 14:43:06] [fail] WebSocket Connection [::ffff:<client.adress>]:50695 - "" - 0 websocketpp.transport:8 TLS Short Read
[2016-07-06 14:43:06] [error] handle_read_handshake error: websocketpp.transport:8 (TLS Short Read)
[2016-07-06 14:43:06] [fail] WebSocket Connection [::ffff:<client.adress>]:50696 - "" - 0 websocketpp.transport:8 TLS Short Read
[2016-07-06 14:43:07] [http] <server.adress>:5601 [::ffff:<client.adress>]:50698 "GET /js/login.chunk.js HTTP/1.1" 200 2827 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
[2016-07-06 14:43:07] [http] <server.adress>:5601 [::ffff:<client.adress>]:50697 "GET /images/background_1500px.jpg HTTP/1.1" 200 308781 "Mozilla/5.0 (WindowsNT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
[2016-07-06 14:43:08] [error] handle_read_handshake error: websocketpp.transport:8 (TLS Short Read)
[2016-07-06 14:43:08] [fail] WebSocket Connection [::ffff:<client.adress>]:50699 - "" - 0 websocketpp.transport:8 TLS Short Read
[2016-07-06 14:43:08] [http] <server.adress>:5601 [::ffff:<client.adress>]:50700 "GET /favicon.ico HTTP/1.1" 200 53158 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
[2016-07-06 14:43:21] [error] handle_read_handshake error: websocketpp.transport:8 (TLS Short Read)
[2016-07-06 14:43:21] [error] handle_read_handshake error: websocketpp.transport:8 (TLS Short Read)
[2016-07-06 14:43:21] [fail] WebSocket Connection [::ffff:<client.adress>]:50701 - "" - 0 websocketpp.transport:8 TLS Short Read
[2016-07-06 14:43:21] [connect] WebSocket Connection [::ffff:<client.adress>]:50702 v13 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36" / 101
[2016-07-06 14:43:21] [error] handle_read_handshake error: websocketpp.transport:8 (TLS Short Read)
[2016-07-06 14:43:21] [fail] WebSocket Connection [::ffff:<client.adress>]:50703 - "" - 0 websocketpp.transport:8 TLS Short Read
[2016-07-06 14:43:21] [http] <server.adress>:5601 [::ffff:<client.adress>]:50704 "GET /js/home.chunk.js HTTP/1.1" 200 2875 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
[2016-07-06 14:43:22] [error] handle_read_handshake error: websocketpp.transport:8 (TLS Short Read)
[2016-07-06 14:43:22] [fail] WebSocket Connection [::ffff:<client.adress>]:50705 - "" - 0 websocketpp.transport:8 TLS Short Read
[2016-07-06 14:43:22] [http] <server.adress>:5601 [::ffff:<client.adress>]:50706 "GET /images/AirDCPlusPlus.png HTTP/1.1" 200 17600 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
[2016-07-06 14:44:16] [error] handle_read_handshake error: websocketpp.transport:8 (TLS Short Read)
[2016-07-06 14:44:16] [fail] WebSocket Connection [::ffff:<client.adress>]:50707 - "" - 0 websocketpp.transport:8 TLS Short Read
[2016-07-06 14:44:16] [http] <server.adress>:5601 [::ffff:<client.adress>]:50708 "GET /js/queue.chunk.js HTTP/1.1" 200 10361 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
[2016-07-06 14:44:23] [error] handle_read_handshake error: websocketpp.transport:8 (TLS Short Read)
[2016-07-06 14:44:23] [fail] WebSocket Connection [::ffff:<client.adress>]:50709 - "" - 0 websocketpp.transport:8 TLS Short Read
[2016-07-06 14:44:23] [http] <server.adress>:5601 [::ffff:<client.adress>]:50710 "GET /js/settings.chunk.js HTTP/1.1" 200 6920 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
[2016-07-06 14:44:23] [error] handle_read_handshake error: websocketpp.transport:8 (TLS Short Read)
[2016-07-06 14:44:23] [fail] WebSocket Connection [::ffff:<client.adress>]:50711 - "" - 0 websocketpp.transport:8 TLS Short Read
[2016-07-06 14:44:23] [http] <server.adress>:5601 [::ffff:<client.adress>]:50712 "GET /js/settings-children.chunk.js HTTP/1.1" 200 97157 "Mozilla/5.0 (WindowsNT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
[2016-07-06 14:44:23] [error] handle_read_handshake error: websocketpp.transport:8 (TLS Short Read)
[2016-07-06 14:44:23] [fail] WebSocket Connection [::ffff:<client.adress>]:50713 - "" - 0 websocketpp.transport:8 TLS Short Read
[2016-07-06 14:44:23] [http] <server.adress>:5601 [::ffff:<client.adress>]:50714 "GET /js/settings-profile-children.chunk.js HTTP/1.1" 200 3725 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
11
pid: 6488
Collecting crash information, please wait...
airdcppd in function cow::StackTrace::generate_frames() in file /home/xxxx/Programs/airdcpp-webclient/airdcppd/stacktrace.cpp:44 [0x2cdee]
airdcppd in function __gnu_cxx::__normal_iterator<cow::StackFrame*, std::vector<cow::StackFrame, std::allocator<cow::StackFrame> > >::__normal_iterator(cow::StackFrame* const&) in file /usr/include/c++/5/bits/stl_iterator.h:741 [0x294ae]
/lib/arm-linux-gnueabihf/libc.so.6 in function [unknown] [0x765af250]
/usr/local/lib/libairdcpp-webapi.so.1.0.6 in function std::_Rb_tree_iterator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long long, unsigned long long, double, std::allocator> > > std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long long, unsigned long long, double, std::allocator> >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long long, unsigned long long, double, std::allocator> > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long long, unsigned long long, double, std::allocator> > > >::_M_emplace_hint_unique<std::piecewise_construct_t const&, std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>, std::tuple<> >(std::_Rb_tree_const_iterator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long long, unsigned long long, double, std::allocator> > >, std::piecewise_construct_t const&, std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>&&, std::tuple<>&&) [0x76db46e2]
/usr/local/lib/libairdcpp-webapi.so.1.0.6 in function nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long long, unsigned long long, double, std::allocator>::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) [0x76dfc218]
/usr/local/lib/libairdcpp-webapi.so.1.0.6 in function [unknown] [0x76e09700]
/usr/local/lib/libairdcpp-webapi.so.1.0.6 in function webserver::SettingApi::parseSettingKeys(nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long long, unsigned long long, double, std::allocator> const&, std::function<void (webserver::ApiSettingItem const*)>) [0x76e09160]
/usr/local/lib/libairdcpp-webapi.so.1.0.6 in function webserver::SettingApi::handleGetSettingInfos(webserver::ApiRequest&) [0x76e09de0]
/usr/local/lib/libairdcpp-webapi.so.1.0.6 in function webserver::ApiModule::handleRequest(webserver::ApiRequest&) [0x76e265b8]
/usr/local/lib/libairdcpp-webapi.so.1.0.6 in function webserver::Session::handleRequest(webserver::ApiRequest&) [0x76db82f2]
/usr/local/lib/libairdcpp-webapi.so.1.0.6 in function webserver::ApiRouter::handleRequest(webserver::ApiRequest&, bool, std::shared_ptr<webserver::WebSocket> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) [0x76df0f08]
/usr/local/lib/libairdcpp-webapi.so.1.0.6 in function webserver::ApiRouter::handleSocketRequest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<webserver::WebSocket>&, bool) [0x76df12f0]

Exception info to be posted on the bug tracker has also been saved in /home/xxxx/.airdc++/exceptioninfo.txt
Press enter to continue

xxxx@xxxx:~$
```

**Comment by maksis** [comment]
Could you confirm that this still happens with the develop branch?

https://airdcpp-web.github.io/docs/installation/compiling.html#installing-a-development-version

**Comment by NEMO1911** [comment]
I can do a test it takes a couple of hours to compile

**Comment by NEMO1911** [comment]
Compile Done, now running the latest develop branch and still experiencing the same problem.

```
Application version
AirDC++w 1.0.6-44-gfbf6 armv7l
Web UI version
1.0.7
Web UI build date
June 24, 2016 9:53 AM
```

**Comment by maksis** [comment]
I've pushed some fixes to the develop branch. Could you test them?

**Comment by NEMO1911** [comment]
OK I'll do so, back in 4h ^^

**Comment by maksis** [comment]
There are only three files to recompile so it shouldn't take hours

**Comment by NEMO1911** [comment]
I noticed, same problem still after compiling to latest.

```
Application version
AirDC++w 1.0.6-46-g94d0 armv7l
Web UI version
1.0.7
Web UI build date
June 24, 2016 9:53 AM
```

```
xxx@xxx:~$ airdcppd
Starting.
.Loading Hash database
Loading Download queue
Loading Shared files
Loading Country information
Starting web server.
AirDC++w 1.0.6-46-g94d0 running, press ctrl-c to exit...
HTTP port: 5600, HTTPS port: 5601
[2016-07-08 17:52:54] [http] <server.adress>:5600 [::ffff:<client.adress>]:51452 "GET / HTTP/1.1" 200 994 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36"
[2016-07-08 17:52:54] [http] <server.adress>:5600 [::ffff:<client.adress>]:51453 "GET /js/main.entry.js HTTP/1.1" 200 1833897 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36"
[2016-07-08 17:52:56] [http] <server.adress>:5600 [::ffff:<client.adress>]:51455 "GET /js/home.chunk.js HTTP/1.1" 200 2875 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36"
[2016-07-08 17:52:56] [http] <server.adress>:5600 [::ffff:<client.adress>]:51456 "GET /images/background_3460px.jpg HTTP/1.1" 200 521485 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36"
[2016-07-08 17:52:56] [connect] WebSocket Connection [::ffff:<client.adress>]:51457 v13 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36" / 101
[2016-07-08 17:52:56] [disconnect] Disconnect close local:[1000] remote:[1005]
[2016-07-08 17:52:56] [http] <server.adress>:5600 [::ffff:<client.adress>]:51458 "GET /js/login.chunk.js HTTP/1.1" 200 2827 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36"
[2016-07-08 17:53:24] [connect] WebSocket Connection [::ffff:<client.adress>]:51459 v13 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36" / 101
[2016-07-08 17:53:24] [http] <server.adress>:5600 [::ffff:<client.adress>]:51460 "GET /images/AirDCPlusPlus.png HTTP/1.1" 200 17600 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36"
[2016-07-08 17:53:35] [http] <server.adress>:5600 [::ffff:<client.adress>]:51461 "GET /js/transfers.chunk.js HTTP/1.1" 200 11461 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36"
[2016-07-08 17:53:40] [http] <server.adress>:5600 [::ffff:<client.adress>]:51462 "GET /js/settings.chunk.js HTTP/1.1" 200 6920 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36"
[2016-07-08 17:53:40] [http] <server.adress>:5600 [::ffff:<client.adress>]:51463 "GET /js/settings-children.chunk.js HTTP/1.1" 200 97157 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36"
[2016-07-08 17:53:40] [http] <server.adress>:5600 [::ffff:<client.adress>]:51464 "GET /js/settings-profile-children.chunk.js HTTP/1.1" 200 3725 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36"
11
pid: 5851
Collecting crash information, please wait...
airdcppd in function cow::StackTrace::generate_frames() in file /home/nemo/Programs/airdcpp-webclient/airdcppd/stacktrace.cpp:44 [0x2cdf2]
airdcppd in function __gnu_cxx::__normal_iterator<cow::StackFrame*, std::vector<cow::StackFrame, std::allocator<cow::StackFrame> > >::__normal_iterator(cow::StackFrame* const&) in file /usr/include/c++/5/bits/stl_iterator.h:741 [0x294ae]
/lib/arm-linux-gnueabihf/libc.so.6 in function [unknown] [0x7661e250]
/usr/local/lib/libairdcpp-webapi.so.1.0.6 in function std::_Rb_tree_iterator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long long, unsigned long long, double, std::allocator> > > std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long long, unsigned long long, double, std::allocator> >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long long, unsigned long long, double, std::allocator> > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long long, unsigned long long, double, std::allocator> > > >::_M_emplace_hint_unique<std::piecewise_construct_t const&, std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>, std::tuple<> >(std::_Rb_tree_const_iterator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long long, unsigned long long, double, std::allocator> > >, std::piecewise_construct_t const&, std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>&&, std::tuple<>&&) [0x76e25f76]
/usr/local/lib/libairdcpp-webapi.so.1.0.6 in function nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long long, unsigned long long, double, std::allocator>::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) [0x76e6ddac]
/usr/local/lib/libairdcpp-webapi.so.1.0.6 in function [unknown] [0x76e7ae48]
/usr/local/lib/libairdcpp-webapi.so.1.0.6 in function webserver::SettingApi::parseSettingKeys(nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long long, unsigned long long, double, std::allocator> const&, std::function<void (webserver::ApiSettingItem const*)>) [0x76e7b9a2]
/usr/local/lib/libairdcpp-webapi.so.1.0.6 in function webserver::SettingApi::handleGetSettingInfos(webserver::ApiRequest&) [0x76e7bc04]
/usr/local/lib/libairdcpp-webapi.so.1.0.6 in function webserver::ApiModule::handleRequest(webserver::ApiRequest&) [0x76e98838]
/usr/local/lib/libairdcpp-webapi.so.1.0.6 in function webserver::Session::handleRequest(webserver::ApiRequest&) [0x76e29cb2]
/usr/local/lib/libairdcpp-webapi.so.1.0.6 in function webserver::ApiRouter::handleRequest(webserver::ApiRequest&, bool, std::shared_ptr<webserver::WebSocket> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) [0x76e629f8]
/usr/local/lib/libairdcpp-webapi.so.1.0.6 in function webserver::ApiRouter::handleSocketRequest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::shared_ptr<webserver::WebSocket>&, bool) [0x76e62e16]

Exception info to be posted on the bug tracker has also been saved in /home/nemo/.airdc++/exceptioninfo.txt
Press enter to continue

xxx@xxx:~$
```

**Comment by maksis** [comment]
Oh, I may have mistaken about the code location because there are no line numbers in the log.

Could you get a better stack trace with gdb:

```
gdb airdcppd
run
[crash]
bt full
```

**Comment by NEMO1911** [comment]
Can't seam to fully get gdb to work.
```
$ gdb airdcppd


(gdb) run
Starting program: /usr/local/bin/airdcppd

Program received signal SIGSEGV, Segmentation fault.
0x76fd9822 in ?? () from /lib/ld-linux-armhf.so.3
(gdb) by full
#0  0x76fd9822 in ?? () from /lib/ld-linux-armhf.so.3
No symbol table info available.
#1  0x76fd983a in ?? () from /lib/ld-linux-armhf.so.3
No symbol table info available.
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```
I can't connect to the core from the browser and test out anything when running it in gdb, I tried to find some more info on this but doesn't seem to help.

If I first run: handle SIGSEGV nostop

I get the following:
```
Signal        Stop      Print   Pass to program Description
SIGSEGV       No        Yes     Yes             Segmentation fault
(gdb) file /usr/local/bin/airdcppd
Reading symbols from /usr/local/bin/airdcppd...done.
(gdb) run
Starting program: /usr/local/bin/airdcppd

Program received signal SIGSEGV, Segmentation fault.

Program terminated with signal SIGSEGV, Segmentation fault.
The program no longer exists.
(gdb)

```

**Comment by maksis** [comment]
So it crashes right away when you typed `run`? Did you type `by full` instead of `bt full`?

Alternatively you could also try running and crashing the client normally. Instead of pressing enter after client has crashed, you should run gdb:

```
sudo gdb
attach [client PID]
thread apply all bt full
```

**Comment by maksis** [comment]
The client seems to be running normally according to that log. Did you really crash it first?

**Comment by NEMO1911** [comment]
Yes I did the same steps as before and i made sure it said `Press enter to continue` i terminal before I ran the gdb command.

**Comment by maksis** [comment]
I wonder if the crash happened on one of the threads only displaying `Backtrace stopped: previous frame identical to this frame (corrupt stack?)`. If this is caused by stack corruption, it may also be related #141.

**Comment by NEMO1911** [comment]
If I attached to airdcppd before i crashed the program I would lose the connection to it in the browser and thus not be able to crash it.

**Comment by NEMO1911** [comment]
How to figure out if its a stack corruption? if there is anything else i can test or if you want access to the box to do some testing yourself just tell me, Its empty and I'm not running anything on it atm.

**Comment by maksis** [comment]
You could first try getting memory error information with valgrind:

`valgrind airdcppd`

If it stops because there were many warnings from OpenSSL (libcrypto) as happened in https://github.com/airdcpp-web/airdcpp-webclient/issues/141#issuecomment-220634632, try suppressing warnings from that library:

http://stackoverflow.com/questions/3174468/is-it-possible-to-make-valgrind-ignore-certain-libraries
https://www.64k-tec.de/2010/10/using-suppression-files-with-valgrind/

**Comment by maksis** [comment]
And sure, I can also try debugging it

**Comment by NEMO1911** [comment]
I have sent you a email :)

**Comment by maksis** [comment]
I'm quite sure that this is the same issue as #141 so I'll merge this into it. You should subscribe to that issue for further updates (I've been able to narrow it down a bit already).
