### ISSUE TITLE
TypeErrors

### ISSUE THREAD

**Issue by maltenizer** [airdcpp-web/airdcpp-webclient#386]
Application version
AirDC++w 2.11.1b x86_64
Web UI version
2.11.1-beta.1
Web UI build date
January 21, 2021 8:39 PM

Browser: Google Chrome Version 88.0.4324.190 (Officiell version) (64 bitar) on WIndows Server 2016 version 1607
Crashing have also happened on older versions of chrome.

CentOS Linux release 7.9.2009 (Core)

WebUI crashes after some time with either of these two errors:

Web UI has crashed with the following error: "TypeError: Cannot read property 'nicks' of undefined"
Web UI has crashed with the following error: "TypeError: Cannot read property 'country' of undefined"

It has always been crashing when i'm not using the browser.

**Comment by maltenizer** [comment]
I found the culprit.

Newer chrome have a flag in chrome://flags, "Throttle Javascript timers in background."
It throttle javascript in the background tabs or non active windows and that breaks webui in airdc.
If i disable the flag it works as normal.

Description in chrome:

Throttle Javascript timers in background.
When enabled, wake ups from DOM Timers are limited to 1 per minute in a page that has been hidden for 5 minutes. For additional details, see https://www.chromestatus.com/feature/4718288976216064. – Mac, Windows, Linux, Chrome OS, Android

This flag is enabled as default in chrome.

**Comment by maksis** [comment]
Please include the stack trace from the browser console according to https://github.com/airdcpp-web/airdcpp-webclient/blob/master/.github/CONTRIBUTING.md#ui-related-issues

**Comment by maksis** [comment]
I've released builds with a new UI version that will show the full stack trace without the need to get it from the console. This issue will be closed without further information as I haven't heard of anyone else experiencing the same crash.

**Comment by maltenizer** [comment]
Web UI has crashed
Please submit a bug report with the requested information (and the crash details below) at the issue tracker.

Crash details
TypeError: Cannot read property 'country' of undefined
    at t.a (https://seedbox:5601/js/favorite-hubs~filelists~hubs~queue~search~share~transfers.33569bcc0a71763d4b28.chunk.js:1:184820)
    at ia (https://seedbox:5601/js/main.9c90215436bb7c9782cf.entry.js:100:58877)
    at GA (https://seedbox:5601/js/main.9c90215436bb7c9782cf.entry.js:100:111313)
    at ys (https://seedbox:5601/js/main.9c90215436bb7c9782cf.entry.js:100:98325)
    at Bs (https://seedbox:5601/js/main.9c90215436bb7c9782cf.entry.js:100:98253)
    at ws (https://seedbox:5601/js/main.9c90215436bb7c9782cf.entry.js:100:98116)
    at ds (https://seedbox:5601/js/main.9c90215436bb7c9782cf.entry.js:100:95103)
    at https://seedbox:5601/js/main.9c90215436bb7c9782cf.entry.js:100:44772
    at t.unstable_runWithPriority (https://seedbox:5601/js/main.9c90215436bb7c9782cf.entry.js:108:3768)
    at _n (https://seedbox:5601/js/main.9c90215436bb7c9782cf.entry.js:100:44549)
