### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'nicks') 

### ISSUE THREAD

**Issue by Big-Daddio** [airdcpp-web/airdcpp-webclient#474]
### Current UI and client versions:
4.21

### Operating system:

win 11 pro

### Steps to reproduce the issue:

at some point overnight while the webui was open received this error ,  browser was  running on another laptop win 11 pro Chrome 
Version 126.0.6478.127 (Official Build) (64-bit)

### Screenshots
Crash details

TypeError: Cannot read properties of undefined (reading 'nicks')
    at G (https://pixie-pc:5601/js/transfers.8d1840e604ad0e4c0c15.chunk.js:1:7411)
    at ka (https://pixie-pc:5601/js/main.560335911ba879ef8877.entry.js:2:2338934)
    at ks (https://pixie-pc:5601/js/main.560335911ba879ef8877.entry.js:2:2395766)
    at vu (https://pixie-pc:5601/js/main.560335911ba879ef8877.entry.js:2:2384918)
    at Cu (https://pixie-pc:5601/js/main.560335911ba879ef8877.entry.js:2:2384846)
    at gu (https://pixie-pc:5601/js/main.560335911ba879ef8877.entry.js:2:2384709)
    at uu (https://pixie-pc:5601/js/main.560335911ba879ef8877.entry.js:2:2381850)
    at Yn (https://pixie-pc:5601/js/main.560335911ba879ef8877.entry.js:2:2322780)
    at ou (https://pixie-pc:5601/js/main.560335911ba879ef8877.entry.js:2:2378950)
    at Object.enqueueForceUpdate (https://pixie-pc:5601/js/main.560335911ba879ef8877.entry.js:2:2330086)

**Comment by Big-Daddio** [comment]
just had another one - it is a newish install about a week or two old, been hashing/indexing 40TB, but this seems to have only started happening today after I enabled and started using SSL in the config...

error as follows...
 
Web UI has crashed
Please submit a bug report with the requested information (and the crash details below) at the [issue tracker](https://github.com/airdcpp-web/airdcpp-webclient/issues).

Crash details
TypeError: Cannot read properties of undefined (reading 'country')
    at a (https://pixie-pc:5601/js/424.b9b775d50fbed2ec85ca.chunk.js:1:9195)
    at ka (https://pixie-pc:5601/js/main.560335911ba879ef8877.entry.js:2:2338934)
    at ks (https://pixie-pc:5601/js/main.560335911ba879ef8877.entry.js:2:2395766)
    at vu (https://pixie-pc:5601/js/main.560335911ba879ef8877.entry.js:2:2384918)
    at Cu (https://pixie-pc:5601/js/main.560335911ba879ef8877.entry.js:2:2384846)
    at gu (https://pixie-pc:5601/js/main.560335911ba879ef8877.entry.js:2:2384709)
    at uu (https://pixie-pc:5601/js/main.560335911ba879ef8877.entry.js:2:2381850)
    at Yn (https://pixie-pc:5601/js/main.560335911ba879ef8877.entry.js:2:2322780)
    at ou (https://pixie-pc:5601/js/main.560335911ba879ef8877.entry.js:2:2378950)
    at Object.enqueueForceUpdate (https://pixie-pc:5601/js/main.560335911ba879ef8877.entry.js:2:2330086)

**Comment by Big-Daddio** [comment]
seems to be an SSL thing, I have disabled SSL and seems to be back to working properly?

**Comment by maksis** [comment]
> seems to be an SSL thing, I have disabled SSL and seems to be back to working properly?

If you are using the default self-signed certificate, it may be causing issues with browsers. I see no reason why you should use encryption in a local network though.
