### ISSUE TITLE
NPM error

### ISSUE THREAD

**Issue by Kcchouette** [airdcpp-web/airdcpp-webclient#80]
Error during the install

```
Installing version 0.16. of Web UI
npm ERR! Error: version not found: airdcpp-webui@0.16.3
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:125:12
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "--prefix" "." "airdcpp-webui@0.16.3"
npm ERR! cwd /home/user/projects/airdcpp-webclient
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/user/projects/airdcpp-webclient/npm-debug.log
npm ERR! not ok code 0
```

If you want the full log, do not hesitate to ask!

**Comment by Kcchouette** [comment]
I have manually fix the problem by doing: ```npm install --prefix . airdcpp-webui@0.16.2``` which are the latest version on https://www.npmjs.com/package/airdcpp-webui

**Comment by maksis** [comment]
Please pull the latest changes for a fixed installation script

**Comment by Kcchouette** [comment]
Thanks! :+1:
